# Generated by Django 5.0.6 on 2024-06-27 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=255)),
                ('total_no_of_workshop_conducted', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=255)),
                ('total_no_of_workshop_conducted', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.TextField()),
                ('student_name', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('course_registered', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField()),
                ('no_of_workshop_attended', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop_name', models.CharField(max_length=255)),
                ('conducted_by', models.CharField(max_length=255)),
                ('workshop_date', models.DateField()),
                ('workshop_location', models.CharField(max_length=255)),
                ('resource', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APrimeApp.category')),
                ('conducted_by_department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APrimeApp.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waitlist', models.TextField()),
                ('confirmed_registration', models.TextField()),
                ('total_seats', models.IntegerField()),
                ('seats_filled', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APrimeApp.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
