# Generated by Django 5.0.6 on 2024-07-03 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APrimeApp", "0002_alter_category_total_no_of_workshop_conducted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="workshop_start_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
