# Generated by Django 5.0.6 on 2024-07-03 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APrimeApp", "0003_workshop_workshop_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="workshop_end_time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="workshop_start_time",
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
