# Generated by Django 5.0.6 on 2024-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APrimeApp', '0004_workshop_workshop_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='no_of_workshop_waitlisted',
            field=models.IntegerField(default=0),
        ),
    ]
