# Generated by Django 5.0.6 on 2024-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APrimeApp', '0005_student_no_of_workshop_waitlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='no_of_workshop_scheduled',
            field=models.IntegerField(default=0),
        ),
    ]
