# Generated by Django 5.0.6 on 2024-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APrimeApp', '0006_student_no_of_workshop_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
