# Generated by Django 5.0.7 on 2024-07-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APrimeApp', '0007_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
